name: unifi-cli
base: core18
version: '0.1.0'
summary: Unifi Commandline inferface to manage Unifi controller
description: |
  Unifi controller have it own dashboard to manage the network. But it
  require a commandline interface to access certain functions like SSL
  certificates.

grade: devel
confinement: classic

apps:
  unifi-cli:
    command: sh $SNAP/bin/unifi

parts:
  unifi-cli:
    source: .
    plugin: dump
    organize:
      bin/unifi.sh: bin/unifi
